scss_files: '**/*.scss'

exclude: 'css/layout.scss'

linters:
  SelectorFormat:
    enabled: false
  ColorVariable:
    enabled: false
  ColorKeyword:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  ImportantRule:
    enabled: false
  UrlFormat:
    enabled: false