title: 37 Commits
email: me@37commits.com
description: >
  A catalog of developer helpful ideas
baseurl: ""
url: "http://37commits.com"
markdown: kramdown
author:
  name: "Bohdan Snisar"
  email: me@37commits.com
encoding: utf-8
timezone: America/San_Francisco
permalink: :year/:month/:day/:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->


sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false